/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package questionapp;

import javax.swing.ButtonGroup;

/**
 *
 * @author x17363253
 */
public class QuestionGUI extends javax.swing.JPanel {

    /**
     * Creates new form QuestionGUI
     */
    public QuestionGUI() {
        
        initComponents();
        q1ButtonGroup();
        
    }
    
    private void q1ButtonGroup(){
        ButtonGroup bg1 = new ButtonGroup();
        
        bg1.add(TrueQ1);
        bg1.add(FalseQ1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jCheckBox1 = new javax.swing.JCheckBox();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SubmitBTN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TrueQ1 = new javax.swing.JRadioButton();
        FalseQ1 = new javax.swing.JRadioButton();
        TrueQ2 = new javax.swing.JRadioButton();
        FalseQ2 = new javax.swing.JRadioButton();
        TrueQ3 = new javax.swing.JRadioButton();
        FalseQ3 = new javax.swing.JRadioButton();
        TrueQ5 = new javax.swing.JRadioButton();
        TrueQ4 = new javax.swing.JRadioButton();
        FalseQ4 = new javax.swing.JRadioButton();
        FalseQ5 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        DisplayBTN = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        jLabel1.setText("Q.1");

        jLabel2.setText("Q.2");

        jLabel3.setText("Q.3");

        jLabel4.setText("Q.4");

        jLabel5.setText("Q.5");

        SubmitBTN.setText("Submit");
        SubmitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBTNActionPerformed(evt);
            }
        });

        jLabel6.setText("jLabel6");

        TrueQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrueQ1ActionPerformed(evt);
            }
        });

        TrueQ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrueQ2ActionPerformed(evt);
            }
        });

        TrueQ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrueQ3ActionPerformed(evt);
            }
        });

        TrueQ5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrueQ5ActionPerformed(evt);
            }
        });

        TrueQ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrueQ4ActionPerformed(evt);
            }
        });

        FalseQ5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FalseQ5ActionPerformed(evt);
            }
        });

        jLabel7.setText("jLabel6");

        jLabel8.setText("jLabel6");

        jLabel9.setText("jLabel6");

        jLabel10.setText("jLabel6");

        jLabel11.setText("TRUE/FALSE");

        jLabel12.setText("QUESTIONAIRE");

        DisplayBTN.setText("Display");
        DisplayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(TrueQ1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(TrueQ2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(TrueQ3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(TrueQ5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(TrueQ4)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FalseQ1)
                            .addComponent(FalseQ2)
                            .addComponent(FalseQ3)
                            .addComponent(FalseQ4)
                            .addComponent(FalseQ5))))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(SubmitBTN)
                        .addGap(53, 53, 53)
                        .addComponent(DisplayBTN)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel12)
                .addGap(32, 32, 32)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel6)
                        .addComponent(TrueQ1))
                    .addComponent(FalseQ1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel8))
                    .addComponent(TrueQ2)
                    .addComponent(FalseQ2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel9))
                    .addComponent(TrueQ3)
                    .addComponent(FalseQ3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TrueQ4)
                    .addComponent(FalseQ4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7))
                    .addComponent(TrueQ5)
                    .addComponent(FalseQ5))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitBTN)
                    .addComponent(DisplayBTN))
                .addContainerGap(107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TrueQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrueQ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrueQ1ActionPerformed

    private void TrueQ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrueQ2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrueQ2ActionPerformed

    private void TrueQ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrueQ3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrueQ3ActionPerformed

    private void TrueQ5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrueQ5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrueQ5ActionPerformed

    private void TrueQ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrueQ4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrueQ4ActionPerformed

    private void FalseQ5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FalseQ5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FalseQ5ActionPerformed

    private void SubmitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBTNActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
    }//GEN-LAST:event_SubmitBTNActionPerformed

    private void DisplayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayBTNActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
        
    }//GEN-LAST:event_DisplayBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DisplayBTN;
    private javax.swing.JRadioButton FalseQ1;
    private javax.swing.JRadioButton FalseQ2;
    private javax.swing.JRadioButton FalseQ3;
    private javax.swing.JRadioButton FalseQ4;
    private javax.swing.JRadioButton FalseQ5;
    private javax.swing.JButton SubmitBTN;
    private javax.swing.JRadioButton TrueQ1;
    private javax.swing.JRadioButton TrueQ2;
    private javax.swing.JRadioButton TrueQ3;
    private javax.swing.JRadioButton TrueQ4;
    private javax.swing.JRadioButton TrueQ5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
